[project]
name = "mix-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.1",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
]
